#
# Travis Project Descriptor
#
# See http://docs.travis-ci.com/user/build-configuration/
#

# DBus on precise is way too old…
dist: trusty
sudo: required

# build matrix
language: python
python:
    - "2.7"
    - "3.4"
#    - "pypy"
#matrix:
#    # Do not allow failures for Python 3 when you create "universal" wheels (see 'setup.cfg')
#    allow_failures:
#        - python: "3.4"

# command to install dependencies
install:
    - sudo apt-get install build-essential libdbus-glib-1-dev python-dev libffi-dev
    - "pip install -r dev-requirements.txt"
    - "pip install secretstorage dbus-python"
    - "python setup.py develop -U"
# command to run tests
script: invoke --echo --pty ci

# report to coveralls.io
after_success:
    - coveralls --rcfile project.d/coverage.cfg
